modLoader = "javafml"
loaderVersion = "*"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/cev-api/Voxelmap/issues"

[[mods]]
modId = "voxelmap-cevapi"
version = "${version}"
displayName = "VoxelMap x SeedMapper by CevAPI"
logoFile = "icon.png"
authors = "CevAPI, Lahwran, Zaneris, MamiyaOtaru, fantahund, Brokkonaut, TheAlgorithm476, Algamja11"
description = "Minimap, World Map & Seed Map"
displayURL = "https://github.com/cev-api/Voxelmap"

[[dependencies.voxelmap]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.160,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.voxelmap]]
modId = "minecraft"
type = "required"
versionRange = "[26.1]"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "mixin.voxelmap.json"

[[mixins]]
config = "mixin.voxelmap.neoforge.json"